### ISSUE TITLE
Better color bar

### ISSUE THREAD

**Issue by livibetter** [alexdantas/nFlood#10]
I think the color options are still not perfect, you still can waste floor moves:

![2014-01-24--12 00 45](https://f.cloud.github.com/assets/30909/1991976/354d1a3e-84ac-11e3-9502-4ba990c48a78.png)

If you choose to floor colors other than blue and red, the moves keep going. So, in the beginning of this game, the color bar should only have blue and red available to be flooded.

The game should check really flood-able color. Maybe using `floor()` also to collect the next possible flood color, kills two birds with one stone.

Anyway, this is no rush to be done.

**Comment by alexdantas** [comment]
I don't quite agree with this.

From the perspective of someone who just started the game for the first time, is nice for him to choose random colors and see the results. If we limit it that way, the game's rules may seem strange.

And for someone that already know the game, he'll only choose the right colors so it won't make a difference.

If anything bad happens, the player can always restart the game. If we're that worried about missing colors, maybe we could implement a `undo()` function. But both alternatives require a considerate amount of work, so I'm not sure.

**Comment by livibetter** [comment]
I am okay with either way, but with your comment, that means that the "no same color" (#5) should also be applied on, meaning, it should be removed.

Maybe close this and open an "undo" issue, also revert (#5)?

**Comment by alexdantas** [comment]
Sorry, I meant we could allow the user to flood wrong colors. That way he could test the game rules.
But it makes sense not to let him use the same color in a row. That fix was a blessing, don't know why I didn't implemented that in the first place.

**Comment by livibetter** [comment]
Okay, then I think this issue has no longer need right since no action or coding is need as current program is. I will leave to you to close this issue, just in case I still get your thought wrong.

By the way, if we do implement `undo()`, then once it's used, the score shouldn't get into high score list since it's kind of cheat, right?

**Comment by alexdantas** [comment]
Yes, `undo()` shouldn't get on high scores
