### ISSUE TITLE
Re-center when window resizing

### ISSUE THREAD

**Issue by livibetter** [alexdantas/nFlood#12]
The board has to be re-centered when the window size changes if centering is used.

**Comment by alexdantas** [comment]
Indeed. I've looked it up and it's a matter of checking for `KEY_RESIZE` on the input loop.
Then we resize based on `getmaxyx()`.

If you let it to me, I'll probably solve it tomorrow.

**Comment by livibetter** [comment]
Sure, I was thinking to wait for a bit before getting started on this, so I left this unassigned when I created this, now it's all yours.

**Comment by alexdantas** [comment]
Agh... Took a lot of work but finally is done. Check out the comment I left there (9abd056003c3b3394497287fa36fb8339de48682).
So, now that the user can specify RGB components of custom colors, I'll add a simple config file tomorrow.

**Comment by livibetter** [comment]
I believe this has been fixed. As for config file, it's listed in #3 and a new issue can be opened for it if needed.

_(trying to issues-- in my opened issues list...)_
