### ISSUE TITLE
Board size

### ISSUE THREAD

**Issue by livibetter** [alexdantas/nFlood#13]
I saw now board size has changed from recent commit. (Done coding on that part?)

So, do we need command-line options like `-W` (`--width`), `-H` (`--height`)?

**Comment by alexdantas** [comment]
Yeah, done.
We'll sure need that.

_just a sidenote_: is the game working out ok for you? Sometimes (like, once in 20 attempts) things get extremely buggy - like colors not flooding right, random characters and stuff.

If that becomes a recurrent issue, I might have to undo my recent commits.

**Comment by livibetter** [comment]
If that happened by mouse clicking on color bar, it's fixed in 2f9f4e433b635afb639f9ded3be6fbab2fe69274, but if not, I haven't seen any like those by keys or clicking on main board.
