### ISSUE TITLE
"nFlood" on board

### ISSUE THREAD

**Issue by livibetter** [alexdantas/nFlood#6]
There is no game title printed on the board, but the text "nFlood" should be seen, and maybe with version if there will be one.

So, where to put it, what should it look like?

**Comment by alexdantas** [comment]
Hmm, that's tricky.

I first thought of showing the title screen and a menu with _Start Game_ or something.
But then a player might simply want to go straight to the game.

So, which one do you think is better:
1. Show a title screen with delay
2. Show a menu with logo

Anyway, we could add a command-line argument to quickly jump to the game... Like `-f / --fast`

**Comment by livibetter** [comment]
I think we need at least a plain text "nFlood" somewhere on screen, so if someone takes a screenshot, at least whoever see the image could guess the name of the game.

**Comment by alexdantas** [comment]
If we ever feel like implementing a title screen (or a nice logo), we'll refer to this issue again.
