### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by livibetter** [alexdantas/nFlood#7]
I think it's time to lay out the coding style because I started to notice the problem, like I used to do `1 + a * 3` instead of `1 + a*3`. Both are fine as long as one style is used throughout the entire code.

Since I am not the project owner, so I list what I have observed the possible style, @alexdantas, please edit this issue directly to fix anything isn't meeting your coding style.
- _Indentation_ with Tabs (tabstop = 4-space), _aligning_ with spaces
- `snake_case` on function and variable names
- Higher precedence operators "glued together": `1 + a*2` and `a*b + c/d`
- No space between function name and parenthesis (`function()` and not `function ()`)
- Comments preferably on C style (`/* ... */`)
- `{}` always has their own lines, align with keywords, such as `if` or `for`, e.g.
  
  ``` c
  if (something())
  {
    something_more();
  }
  ```

**Comment by alexdantas** [comment]
I've always indented everything with tabs, does GitHub messes up so it looks like 8 spaces?

**Comment by livibetter** [comment]
Actually, not really 8, it was just my guessing. I think GitHub renders tab as 2-space. So, I don't think tab is really a good choice if you want to read via GitHub web.

I currently set tab to 8 in Vim whenever I code in C and the coding style is unknown.

You need to specify how many spaces is your tab, or it wouldn't align pretty when it's needed to align with spaces.

**Comment by alexdantas** [comment]
My current setup lays 4 spaces per tab
How many spaces are you used to?

**Comment by livibetter** [comment]
4 is good, I will use that from now on.
