### ISSUE TITLE
Change Versioning System

### ISSUE THREAD

**Issue by alexdantas** [alexdantas/nFlood#8]
Somewhere on the next commits, I suggest we start to use [Semantic Versioning](http://semver.org/).
It's very organized and simple.

I don't know what I had in mind when simply labeled the program 'v1.0'.

**Comment by livibetter** [comment]
I like semver, go for it!

**Comment by alexdantas** [comment]
Done on b7741b29bb6aa794a22955fbf93d28b96dca6362
Will make a release
