### ISSUE TITLE
ChangeLog format

### ISSUE THREAD

**Issue by livibetter** [alexdantas/nFlood#9]
There was a [`ChangeLog`](https://github.com/alexdantas/nFlood/blob/5b2c59073d1460adc0b4dc5c1285cadd37042b57/ChangeLog) and I think we need to bring it back, the question is the format.

I suggest that we use Markdown, that is `ChangeLog.md` and it should include the following information:
- Version string: `x.y.z`
- Release date: `YYYY-MM-DD`
- Log entries: `Add`, `Fix`, `Clean`
  
  Should _include commits/changes other than trivial or tiny fixes_. 
- _Keep current development log_, which will simply be re-sectioned into new release.
  
  I personally like editing ChangeLog as development goes, I always update the log with the commit, so it wouldn't be missing anything when releasing.

Please edit this issue to fix anything.

``` markdown
nFlood ChangeLog
================

## Development

* add high score (#4)

  The saved high score is at `~/.local/share/nflood/nflood.scores`.

* fix something example (#NN by @someone)

  Need to credit the contributor. Also use this indent area for
  extra information, which might be interested.

## Version 0.5.0 (YYYY-MM-DD)

* add command-line options
* add mouse support (#2)
* make board at center 

## Version 0.1 (2012-05-01)

* Game core made. It simply works but has lots of bugs.
```

**Comment by livibetter** [comment]
just noticed [Releases](https://github.com/alexdantas/nFlood/releases), if @alexdantas you prefer that, then I think we don't need ChangeLog.

**Comment by alexdantas** [comment]
I agree with the ChangeLog.
Even though is duplicated information, we might want to keep it along with the GitHub releases.
Just in case someone gets this software by other means, it'll keep them up with the development.

Also, don't think it should be tied to GitHub issues or pull requests.
